#!/usr/bin/env bash

set -e

# ------------------------------------------------------------------------------
# Global variables

DOTBOT_DIR="lib/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Ensure XDG_ env vars are set
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}   # user-specific data files
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}    # user-specific configuration files
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state} # user-specific state files
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}       # user-specific non-essential data files
export XDG_BIN_HOME=${XDG_BIN_HOME:-$HOME/.local/bin}       # user-specific executable files (non-standard var)

# ------------------------------------------------------------------------------
# Determine configurations to apply

DEFAULT_CONFIG="install.conf.yaml"

CONFIGS=()
ARGS=()
for arg in "$@"; do
    case $arg in
        conf*)    CONFIGS+=("install.conf.yaml") ;;
        package*) CONFIGS+=("packages.conf.yaml") ;;
        all)      CONFIGS=("install.conf.yaml" "packages.conf.yaml") ;;
        *)        ARGS+=("$arg") ;;
    esac
done
set -- "${ARGS[@]}"

[[ ${#CONFIGS[@]} -eq 0 ]] && CONFIGS+=("$DEFAULT_CONFIG")

# ------------------------------------------------------------------------------
# Init

cd "${BASEDIR}"

# Update Git submodules
git submodule sync --quiet --recursive
git submodule update --init --recursive

# Run dotbot
for config in "${CONFIGS[@]}"; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
        -d "${BASEDIR}" \
        -c "${config}" \
        "${@}"
done
