#!/usr/bin/env bash

set -e

# ------------------------------------------------------------------------------
# Global variables

DOTBOT_DIR="lib/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Ensure XDG_ env vars are set
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}   # user-specific data files
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}    # user-specific configuration files
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state} # user-specific state files
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}       # user-specific non-essential data files
export XDG_BIN_HOME=${XDG_BIN_HOME:-$HOME/.local/bin}       # user-specific executable files (non-standard var)

# ------------------------------------------------------------------------------
# Determine configurations to apply

DEFAULT_CONFIG="dotbot.d/install.conf.yaml"

os=$(uname -s)
[[ ${os,,} =~ (linux)        ]] && is_linux=1
[[ ${os,,} =~ (cygwin|mingw) ]] && is_windows=1
[[ -x $(command -v apt) ]]      && has_apt=1

_conf_pkg_apt() {
    if [[ $is_linux -eq 1 && $has_apt -eq 1 ]]; then
        CONFIGS+=("dotbot.d/packages-apt.conf.yaml")
    fi
}
_conf_pkg_github() {
    if [[ $is_linux -eq 1 && $has_apt -eq 1 ]]; then
        CONFIGS+=("dotbot.d/packages-github.conf.yaml")
    fi
}
_conf_pkg_go() {
    CONFIGS+=("dotbot.d/packages-go.conf.yaml")
}
_conf_pkg_user() {
    if [[ $is_linux -eq 1 ]]; then
        CONFIGS+=("dotbot.d/packages-user.conf.yaml")
    fi
}
_conf_pkg_win() {
    if [[ $is_windows -eq 1 ]]; then
        CONFIGS+=("dotbot.d/packages-win.conf.yaml")
    fi
}
_conf_pkg_all() {
    _conf_pkg_win
    _conf_pkg_apt
    _conf_pkg_github
    _conf_pkg_go
    _conf_pkg_user
}

CONFIGS=()
ARGS=()
for arg in "$@"; do
    case $arg in
        conf|config)  CONFIGS+=("$DEFAULT_CONFIG") ;;

        packages)  _conf_pkg_all    ;;
          apt)     _conf_pkg_apt    ;;
          github)  _conf_pkg_github ;;
          go)      _conf_pkg_go     ;;
          user)    _conf_pkg_user   ;;
          win)     _conf_pkg_win    ;;

        all)
            CONFIGS+=("$DEFAULT_CONFIG")
            _conf_pkg_all
            ;;

        *)  ARGS+=("$arg") ;;
    esac
done
set -- "${ARGS[@]}"

[[ ${#CONFIGS[@]} -eq 0 ]] && CONFIGS+=("$DEFAULT_CONFIG")

# ------------------------------------------------------------------------------
# Init

cd "${BASEDIR}"

# Don't recursively fetch submodules when not necessary
git config fetch.recurseSubmodules on-demand

# Update Git submodules
git submodule sync --quiet --recursive
git submodule update --init --recursive

# Run dotbot
for config in "${CONFIGS[@]}"; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
        -d "${BASEDIR}" \
        -c "${config}" \
        "${@}"
done
