# Keybindings
keybinding:

  universal:
#    quit: q
#    quit-alt1: <c-c>
#    suspendApp: <c-z>
#    return: <esc>
#    quitWithoutChangingDirectory: Q
#    togglePanel: <tab>
#    prevItem: <up>
#    nextItem: <down>
#    prevItem-alt: k
#    nextItem-alt: j
#    prevPage: ',' # go to previous page in list
    nextPage: ';' # '.' go to next page in list
#    scrollLeft: H
#    scrollRight: L
#    gotoTop: <
#    gotoBottom: '>'
    gotoTop-alt: <disabled> # default: <home>
    gotoBottom-alt: <disabled> # default: <end>
#    toggleRangeSelect: v
#    rangeSelectDown: <s-down>
#    rangeSelectUp: <s-up>
#    prevBlock: <left>
#    nextBlock: <right>
#    prevBlock-alt: h
#    nextBlock-alt: l
#    nextBlock-alt2: <tab>
#    prevBlock-alt2: <backtab>
#    jumpToBlock:
#      - "1"
#      - "2"
#      - "3"
#      - "4"
#      - "5"
#    focusMainView: "0"
#    nextMatch: "n"
#    prevMatch: "N"
#    startSearch: /
#    optionMenu: <disabled>
#    optionMenu-alt1: '?'
#    select: <space>
#    goInto: <enter>
#    confirm: <enter>
#    confirmMenu: <enter>
#    confirmSuggestion: <enter>
#    confirmInEditor: <a-enter>
#    confirmInEditor-alt: <c-s>
#    remove: d
#    new: "n"
#    edit: e
#    openFile: o
#    scrollUpMain: <pgup>
#    scrollDownMain: <pgdown>
#    scrollUpMain-alt1: K
#    scrollDownMain-alt1: J
#    scrollUpMain-alt2: <c-u>
#    scrollDownMain-alt2: <c-d>
#    executeShellCommand: ':'
#    createRebaseOptionsMenu: m
#
#    # 'Files' appended for legacy reasons
#    pushFiles: P
#
#    # 'Files' appended for legacy reasons
#    pullFiles: p
    refresh: '<f5>' # default: 'R'
#    createPatchOptionsMenu: <c-p>
    nextTab: '<end>' # default: ']'
    prevTab: '<home>' # default: '['
    nextScreenMode: ']' # default: '+'  alternative: '='
    prevScreenMode: '[' # default: '_'  alternative: '-'
#    undo: z
#    redo: Z
#    filteringMenu: <c-s>
#    diffingMenu: W
#    diffingMenu-alt: <c-e>
#    copyToClipboard: <c-o>
#    openRecentRepos: <c-r>
#    submitEditorText: <enter>
#    extrasMenu: '@'
#    toggleWhitespaceInDiffView: <c-w>
#    increaseContextInDiffView: '}'
#    decreaseContextInDiffView: '{'
#    increaseRenameSimilarityThreshold: )
#    decreaseRenameSimilarityThreshold: (
#    openDiffTool: <c-t>

#  status:
#    checkForUpdate: u
#    recentRepos: <enter>
#    allBranchesLogGraph: a

  files:
#    commitChanges: c
#    commitChangesWithoutHook: w
#    amendLastCommit: A
#    commitChangesWithEditor: C
#    findBaseCommitForFixup: <c-f>
#    confirmDiscard: x
#    ignoreFile: i
#    refreshFiles: r
#    stashAllChanges: s
#    viewStashOptions: S
#    toggleStagedAll: a
#    viewResetOptions: D
#    fetch: f
    toggleTreeView: 't' # default: '`'
#    openMergeTool: M
#    openStatusFilter: <c-b>
#    copyFileInfoToClipboard: "y"
#    collapseAll: '-'
#    expandAll: =

#  branches:
#    createPullRequest: o
#    viewPullRequestOptions: O
#    copyPullRequestURL: <c-y>
#    checkoutBranchByName: c
#    forceCheckoutBranch: F
#    checkoutPreviousBranch: '-'
#    rebaseBranch: r
#    renameBranch: R
#    mergeIntoCurrentBranch: M
#    moveCommitsToNewBranch: "N"
#    viewGitFlowOptions: i
#    fastForward: f
#    createTag: T
#    pushTag: P
#    setUpstream: u
#    fetchRemote: f
#    sortOrder: s

#  worktrees:
#    viewWorktreeOptions: w

#  commits:
#    squashDown: s
#    renameCommit: r
#    renameCommitWithEditor: R
#    viewResetOptions: g
#    markCommitAsFixup: f
#    createFixupCommit: F
#    squashAboveCommits: S
#    moveDownCommit: <c-j>
#    moveUpCommit: <c-k>
#    amendToCommit: A
#    resetCommitAuthor: a
#    pickCommit: p
#    revertCommit: t
#    cherryPickCopy: C
#    pasteCommits: V
#    markCommitAsBaseForRebase: B
#    tagCommit: T
#    checkoutCommit: <space>
#    resetCherryPick: <c-R>
#    copyCommitAttributeToClipboard: "y"
#    openLogMenu: <c-l>
#    openInBrowser: o
#    viewBisectOptions: b
#    startInteractiveRebase: i
#    selectCommitsOfCurrentBranch: '*'

#  amendAttribute:
#    resetAuthor: a
#    setAuthor: A
#    addCoAuthor: c

#  stash:
#    popStash: g
#    renameStash: r

#  commitFiles:
#    checkoutCommitFile: c

#  main:
#    toggleSelectHunk: a
#    pickBothHunks: b
#    editSelectHunk: E

#  submodules:
#    init: i
#    update: u
#    bulkMenu: b

#  commitMessage:
#    commitMenu: <c-o>
