
new-pane \
    -c "#{pane_current_path}" \
    -X16% -Y17% -x68% -y66% \
    'bash -c "\
        source ${HOME}/.dotfiles/bash_prompt/_prompt_git_pretty.sh; \
        source ${HOME}/.dotfiles/.bash_functions; \
        prompt_git_dyn_graph_width; \
        LINES=($(tput lines)+4) git-graph-status-page --pretty=graph-dyn-t; \
        read -rsn1 \
    "'
