
new-pane \
    -c "#{pane_current_path}" \
    -X2% -Y1 -x97% -y97% \
    'bash -c "\
        source ${HOME}/.dotfiles/bash_prompt/_prompt_git_pretty.sh; \
        prompt_git_dyn_graph_width; \
        lazygit \
    "'
