#!/usr/bin/env bash

# list available aliases
# https://brettterpstra.com/2014/08/04/shell-tricks-one-git-alias-to-rule-them-all/

maxAliasLength=15

git config --global --get-regexp alias |
  grep -i "$1" |
  awk -v nr=2 '{sub(/^alias\./,"")};
    {printf "  \033[1;33m%-'"$maxAliasLength"'s\033[0;37m ", $1};
    {sep=FS}; {for (x=nr; x<=NF; x++) { printf "%s%s", sep, $x; };
    print "\033[0;39m"}'
